apiVersion: v1
kind: ImportCluster
metadata:
  name: bens-ai-stack-cluster
  description: Your imported cluster
spec:
  git_repository:
    provider: github
    credential_name: User-MisterHarrow
    branch: main
    repository: MisterHarrow/ankra-values
  stacks:
  - name: UI-AI-STACK
    manifests:
    - name: open-webui-db-secret
      parents:
      - name: cnpg-cluster-cr
        kind: manifest
      from_file: manifests/open-webui-db-secret.yaml
    - name: cnpg-cluster-cr
      parents:
      - name: cloudnative-pg
        kind: addon
      from_file: manifests/cnpg-cluster-cr.yaml
    - name: knative-serving-cr
      parents:
      - name: knative-operator
        kind: addon
      from_file: manifests/knative-serving-cr.yaml
    - name: embedding-minilm-l6-v2-isvc
      parents:
      - name: kserve
        kind: addon
      from_file: manifests/embedding-minilm-l6-v2-isvc.yaml
    addons:
    - name: cloudnative-pg
      chart_name: cloudnative-pg
      chart_version: 0.24.0
      repository_url: https://cloudnative-pg.io/charts
      namespace: default
      configuration_type: standalone
      configuration:
        from_file: add-ons/cloudnative-pg/values.yaml
    - name: cert-manager
      chart_name: cert-manager
      chart_version: v1.18.2
      repository_url: https://charts.jetstack.io
      namespace: default
      configuration_type: standalone
      configuration:
        from_file: add-ons/cert-manager/values.yaml
    - name: kube-prometheus-stack
      chart_name: kube-prometheus-stack
      chart_version: 75.7.0
      repository_url: https://prometheus-community.github.io/helm-charts
      namespace: default
      configuration_type: standalone
      configuration:
        from_file: add-ons/kube-prometheus-stack/values.yaml
    - name: jupyterhub
      chart_name: jupyterhub
      chart_version: 4.2.1-0.dev.git.7042.h294a43d1
      repository_url: https://jupyterhub.github.io/helm-chart
      namespace: jupyterhub
      configuration_type: standalone
      configuration:
        from_file: add-ons/jupyterhub/values.yaml
      parents:
      - name: cloudnative-pg
        kind: addon
    - name: knative-operator
      chart_name: knative-operator
      chart_version: v1.18.1
      repository_url: https://knative.github.io/operator
      namespace: knative-operator
      configuration_type: standalone
      configuration:
        from_file: add-ons/knative-operator/values.yaml
    - name: kserve-crd
      chart_name: kserve-crd
      chart_version: v0.15.2
      repository_url: oci://ghcr.io/kserve/charts/kserve-crd
      namespace: kserve-crd
      configuration_type: standalone
      configuration:
        from_file: add-ons/kserve-crd/values.yaml
      parents:
      - name: knative-serving-cr
        kind: manifest
    - name: kserve
      chart_name: kserve
      chart_version: v0.15.2
      repository_url: oci://ghcr.io/kserve/charts/kserve
      namespace: kserve
      configuration_type: standalone
      configuration:
        from_file: add-ons/kserve/values.yaml
      parents:
      - name: kserve-crd
        kind: addon
    - name: opentelemetry-collector
      chart_name: opentelemetry-collector
      chart_version: 0.127.2
      repository_url: https://open-telemetry.github.io/opentelemetry-helm-charts
      namespace: default
      configuration_type: standalone
      configuration:
        from_file: add-ons/opentelemetry-collector/values.yaml
      parents:
      - name: kube-prometheus-stack
        kind: addon
    - name: ingress-nginx
      chart_name: ingress-nginx
      chart_version: 4.12.3
      repository_url: https://kubernetes.github.io/ingress-nginx
      namespace: ingress-nginx
      configuration_type: standalone
      configuration:
        from_file: add-ons/ingress-nginx/values.yaml
    - name: open-webui
      chart_name: open-webui
      chart_version: 6.22.0
      repository_url: https://helm.openwebui.com
      namespace: open-webui
      configuration_type: standalone
      configuration:
        from_file: add-ons/open-webui/values.yaml
      parents:
      - name: open-webui-db-secret
        kind: manifest
