---
replicaCount: 1
knative:
  enabled: false
  containerConcurrency: 0
  timeoutSeconds: 300
  responseStartTimeoutSeconds: 300
  idleTimeoutSeconds: 300
  annotations: {}
image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
ollama:
  port: 11434
  gpu:
    enabled: true
    type: nvidia
    number: 1
    mig:
      enabled: false
      devices: {}
  models:
    pull:
      - qwen3:latest
    run:
      - qwen3:latest
    create: []
  insecure: false
  mountPath: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  cloud.google.com/gke-accelerator: nvidia-tesla-t4
podSecurityContext: {}
securityContext: {}
runtimeClassName: ""
service:
  type: ClusterIP
  port: 11434
  nodePort: 31434
  loadBalancerIP: null
  annotations: {}
  labels: {}
deployment:
  labels: {}
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ollama.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    memory: 4096Mi
    cpu: 2000m
  limits:
    memory: 8192Mi
    cpu: 4000m
livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
extraArgs: []
extraEnv:
  - name: NVIDIA_VISIBLE_DEVICES
    value: all
extraEnvFrom: []
persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations: {}
  existingClaim: ""
  size: 8Gi
  storageClass: ""
  volumeMode: ""
  subPath: ""
  volumeName: ""
nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-l4
tolerations: []
affinity: {}
lifecycle: {}
updateStrategy:
  type: Recreate
topologySpreadConstraints: {}
initContainers: []
hostIPC: false
hostPID: false
hostNetwork: false
extraObjects: []
tests:
  enabled: true
  labels: {}
