---
pipelines:
  enabled: false
extraEnvVars:
  - name: OLLAMA_BASE_URLS
    value: http://ollama:11434
  - name: PYTHONPATH
    value: /app/backend/packages
  - name: ENABLE_OTEL
    value: "true"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector:4317
  - name: OTEL_EXPORTER_OTLP_INSECURE
    value: "true"
  - name: OTEL_METRIC_EXPORT_INTERVAL
    value: "5000"
  - name: OPENAI_API_KEY
    value: 0p3n-w3bu!
nameOverride: ""
namespaceOverride: ""
ollama:
  enabled: false
  fullnameOverride: open-webui-ollama
tika:
  enabled: false
ollamaUrls:
  - http://ollama:11434
ollamaUrlsFromExtraEnv: false
websocket:
  enabled: false
  manager: redis
  url: redis://open-webui-redis:6379/0
  nodeSelector: {}
  redis:
    enabled: true
    name: open-webui-redis
    labels: {}
    annotations: {}
    pods:
      labels: {}
      annotations: {}
    image:
      repository: redis
      tag: 7.4.2-alpine3.21
      pullPolicy: IfNotPresent
    command: []
    args: []
    resources: {}
    service:
      containerPort: 6379
      type: ClusterIP
      labels: {}
      annotations: {}
      port: 6379
      nodePort: ""
    tolerations: []
    affinity: {}
    securityContext: {}
redis-cluster:
  enabled: false
  fullnameOverride: open-webui-redis
  auth:
    enabled: false
  replica:
    replicaCount: 3
clusterDomain: cluster.local
annotations: {}
podAnnotations: {}
podLabels: {}
replicaCount: 1
strategy: {}
image:
  repository: ghcr.io/open-webui/open-webui
  tag: ""
  pullPolicy: IfNotPresent
  command:
    - /bin/sh
    - -c
  args:
    - openlit run -- start_server.sh
serviceAccount:
  enable: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
imagePullSecrets: []
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
resources: {}
copyAppData:
  resources: {}
managedCertificate:
  enabled: false
  name: mydomain-chat-cert
  domains:
    - chat.example.com
ingress:
  enabled: false
  class: ""
  annotations: {}
  host: chat.example.com
  additionalHosts: []
  tls: false
  existingSecret: ""
  extraLabels: {}
persistence:
  enabled: true
  size: 20Gi
  existingClaim: ""
  subPath: ""
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  selector: {}
  annotations: {}
  provider: local
  s3:
    accessKey: ""
    secretKey: ""
    secretKeyExistingSecret: ""
    secretKeyExistingSecretKey: ""
    endpointUrl: ""
    region: ""
    bucket: ""
    keyPrefix: ""
  gcs:
    appCredentialsJson: ""
    appCredentialsJsonExistingSecret: ""
    appCredentialsJsonExistingSecretKey: ""
    bucket: ""
  azure:
    endpointUrl: ""
    container: ""
    key: ""
    keyExistingSecret: ""
    keyExistingSecretKey: ""
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
hostAliases: []
service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: ""
  labels: {}
  loadBalancerClass: ""
enableOpenaiApi: true
openaiBaseApiUrl: https://api.openai.com/v1
openaiBaseApiUrls: []
commonEnvVars: []
extraEnvFrom: []
runtimeClassName: ""
volumeMounts:
  initContainer: []
  container:
    - name: packages
      mountPath: /app/backend/packages
extraInitContainers:
  - name: install-openlit
    image: ghcr.io/open-webui/open-webui:main
    command:
      - sh
      - -c
      - pip install --target=/app/backend/packages openlit && echo "OpenLIT
        installed"
    volumeMounts:
      - name: packages
        mountPath: /app/backend/packages
volumes:
  - name: packages
    emptyDir: {}
podSecurityContext: {}
containerSecurityContext: {}
sso:
  enabled: false
  enableSignup: false
  mergeAccountsByEmail: false
  enableRoleManagement: false
  enableGroupManagement: false
  google:
    enabled: false
    clientId: ""
    clientSecret: ""
    clientExistingSecret: ""
    clientExistingSecretKey: ""
  microsoft:
    enabled: false
    clientId: ""
    clientSecret: ""
    clientExistingSecret: ""
    clientExistingSecretKey: ""
    tenantId: ""
  github:
    enabled: false
    clientId: ""
    clientSecret: ""
    clientExistingSecret: ""
    clientExistingSecretKey: ""
  oidc:
    enabled: false
    clientId: ""
    clientSecret: ""
    clientExistingSecret: ""
    clientExistingSecretKey: ""
    providerUrl: ""
    providerName: SSO
    scopes: openid email profile
  roleManagement:
    rolesClaim: roles
    allowedRoles: ""
    adminRoles: ""
  groupManagement:
    groupsClaim: groups
  trustedHeader:
    enabled: false
    emailHeader: ""
    nameHeader: ""
extraResources: []
databaseUrl: ""
postgresql:
  enabled: false
  fullnameOverride: open-webui-postgres
  architecture: standalone
  auth:
    database: open-webui
    postgresPassword: 0p3n-w3bu!
    username: open-webui
    password: 0p3n-w3bu!
  primary:
    persistence:
      size: 1Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
logging:
  level: ""
  components:
    audio: ""
    comfyui: ""
    config: ""
    db: ""
    images: ""
    main: ""
    models: ""
    ollama: ""
    openai: ""
    rag: ""
    webhook: ""
