global:
  librechat:
    existingSecretName: librechat-credentials-env
    existingSecretApiKey: OPENAI_API_KEY
    existingSecretGoogleApiKey: GOOGLE_KEY

rag:
  enabled: true
  existingSecret: librechat-credentials-env #Template: rag.existingSecret
  configEnv:
    DB_PORT: '5432'
    EMBEDDINGS_PROVIDER: openai

image:
  repository: danny-avila/librechat-rag-api-dev-lite
  registry: ghcr.io
  pullPolicy: IfNotPresent
  tag: latest

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: pgvector/pgvector
    tag: pg16
  auth:
    database: librechat-vectordb
    username: postgres
    existingSecret: librechat-vectordb
    existingSecretKey: postgres-password
  primary:
    extraEnv:
      - name: POSTGRES_DB
        value: librechat-vectordb
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: librechat-vectordb
            key: postgres-password
    containerSecurityContext:
      enabled: true
      readOnlyRootFilesystem: false

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000
  annotations: {}

resources: {}

serviceAccount:
  create: false
  name: ''
  annotations: {}

volumeMounts: {}

volumes: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraContainers: {}
