affinity: {}
extraContainers: {}
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: danny-avila/librechat-rag-api-dev-lite
  tag: latest
imagePullSecrets: []
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
postgresql:
  auth:
    database: librechat-vectordb
    existingSecret: librechat-vectordb
    existingSecretKey: postgres-password
    username: postgres
  enabled: true
  image:
    registry: ghcr.io
    repository: bat-bs/bitnami-pgvector
    tag: pg16
rag:
  configEnv:
    DB_PORT: '5432'
    EMBEDDINGS_PROVIDER: openai
  enabled: true
  existingSecret: librechat-credentials-env
resources: {}
securityContext: {}
service:
  annotations: {}
  port: 8000
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []
volumeMounts: {}
volumes: {}
