affinity: {}
fullnameOverride: ''
global:
  librechat:
    existingSecretApiKey: ''
    existingSecretName: librechat-credentials-env

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: danny-avila/librechat
  tag: ''

imagePullSecrets: []

ingress:
  annotations: {}
  className: ''
  enabled: true
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

librechat:
  configEnv:
    PLUGIN_MODELS: deepseek-coder
    DEBUG_PLUGINS: 'true'
    CREDS_KEY: 9e95d9894da7e68dd69c0046caf5343c8b1e80c89609b5a1e40e6568b5b23ce6
    CREDS_IV: ac028c86ba23f4cd48165e0ca9f2c683
    JWT_SECRET: 16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
    JWT_REFRESH_SECRET: eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
    DEFAULT_ADMIN_USERNAME: admin@admin.com
    DEFAULT_ADMIN_PASSWORD: adminadmin
  configYamlContent: |
    version: "1.0.3"
    registration:
      enabled: true
    endpoints:
      custom:
        - name: "Ollama"
          apiKey: ""
          baseURL: "http://ollama:11434"
          models:
            default: ["deepseek-coder"]
            fetch: false
          titleConvo: true
          titleModel: "deepseek-coder"
          summarize: false
          forcePrompt: false
          modelDisplayLabel: "Deepseek (Ollama)
