replicaCount: 1

global:
  librechat:
    existingSecretName: "librechat-credentials-env"
    existingSecretApiKey: OPENAI_API_KEY

librechat:
  configEnv:
    PLUGIN_MODELS: gpt-4,gpt-4-turbo-preview,gpt-4-0125-preview,gpt-4-1106-preview,gpt-4-0613,gpt-3.5-turbo,gpt-3.5-turbo-0125,gpt-3.5-turbo-1106,gpt-3.5-turbo-0613
    DEBUG_PLUGINS: "true"
    CREDS_KEY: 9e95d9894da7e68dd69c0046caf5343c8b1e80c89609b5a1e40e6568b5b23ce6
    CREDS_IV: ac028c86ba23f4cd48165e0ca9f2c683
    JWT_SECRET: 16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
    JWT_REFRESH_SECRET: eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
    ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
    ALLOW_REGISTRATION: "true"
    ALLOW_EMAIL_LOGIN: "true"
    ALLOW_SOCIAL_LOGIN: "true"
  configYamlContent: |
    version: "1.0.3"
    endpoints:
      custom:
        - name: "Ollama"
          baseURL: "http://ollama:11434"
          models:
            default: ["deepseek-coder"]
            fetch: "false"
          userIdQuery: "false"
          titleConvo: "true"
          titleModel: "deepseek-coder"
          summarize: "false"
          forcePrompt: "false"
          modelDisplayLabel: "Deepseek (Ollama)"
  existingSecretName: "librechat-credentials-env"

image:
  repository: danny-avila/librechat
  registry: ghcr.io
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3080
  annotations: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}
tolerations: []
affinity: {}

updateStrategy:
  type: RollingUpdate

lifecycle: {}

podAnnotations: {}
podLabels: {}

volumes: []
volumeMounts: []

librechat-rag-api:
  enabled: false
  embeddingsProvider: openai

mongodb:
  enabled: true
  auth:
    enabled: false
  databases:
    - LibreChat

meilisearch:
  enabled: true
  persistence:
    enabled: true
    storageClass: ""
  image:
    tag: "v1.7.3"
  auth:
    existingMasterKeySecret: "librechat-credentials-env"

