agent:
  name: mongodb-agent-ubi
  version: 108.0.6.8796-1
community-operator-crds:
  enabled: true
createResource: true
database:
  name: mongodb-database
imagePullSecrets: []
mongodb:
  imageType: ubi8
  name: mongodb-community-server
  repo: docker.io/mongodb
operator:
  deploymentName: mongodb-kubernetes-operator
  extraEnvs: []
  name: mongodb-kubernetes-operator
  operatorImageName: mongodb-kubernetes-operator
  podLabels: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 2000
  priorityClassName: ''
  replicas: 1
  resources:
    limits:
      cpu: 1100m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 200Mi
  securityContext: {}
  version: 0.13.0
readinessProbe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.23
registry:
  agent: quay.io/mongodb
  operator: quay.io/mongodb
  pullPolicy: Always
  readinessProbe: quay.io/mongodb
  versionUpgradeHook: quay.io/mongodb
resource:
  members: 3
  name: mongodb-replica-set
  tls:
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h
      renewCertBefore: 720h
    certificateKeySecretRef: tls-certificate
    enabled: false
    sampleX509User: false
    useCertManager: true
    useX509: false
  users: []
  version: 4.4.0
versionUpgradeHook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.10
